### ISSUE TITLE
Add a back to top option

### ISSUE THREAD

**Issue by caraMcG** [caraMcG/abshelterapp#2]
Add a button for a user on mobile/tablet device to automatically scroll smoothly back to the top without having to swipe for days. 
Ideally should appear only once user has begun scrolling.

**Comment by GeorgiosDrivas** [comment]
Hello! To recap, you would like a "back to top" button to be visible only on mobile/tablet devices and only once the user has begun scrolling. When the user clicks on this button, it should lead them at the top of the website with a smooth scrolling.

If I understand the issue correctly, I would like to work on this. Feel free to answer when you would like me to start working on it.

**Comment by caraMcG** [comment]
Hi @GeorgiosDrivas! Thank you for your comment, yes that's exactly the issue. I'll assign this to you now! 😄

**Comment by GeorgiosDrivas** [comment]
Hello again, @caraMcG! I have created a pull request. In its comments I have explained in details the changes I made. I hope it's what you need.

**Comment by caraMcG** [comment]
@GeorgiosDrivas pull request has been merged! It works great, thank you very much!
