### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by caraMcG** [caraMcG/abshelterapp#4]
Update/write README file with below items.

<ul>
<li>About project</li>
<ul>
<li>app to make the search for a dog easier</li>
<li>specific to  Alberta Canada</li>
</ul>
<li>Shelters Included</li>
<ul>
<li>https://aarcs.ca/</li>
<li>https://pawsitivematch.org/</li>
<li>https://www.calgaryhumane.ca/</li>
</ul>
<li>Built with</li>
<li>Acknowledgements</li>
<ul>
<li>font awesome</li>
<li>Flexbox guide: https://css-tricks.com/snippets/css/a-guide-to-flexbox/#aa-flexbox-properties</li>
<li>Github Pages: https://pages.github.com/</li>
</ul>
<li>Anything else  that may be good to include in a readme doc</li>
</ul>

**Comment by katewar** [comment]
Hi! I'd like to do this, would you mind assigning me?

**Comment by caraMcG** [comment]
@katewar now assigned to you! 😄

**Comment by caraMcG** [comment]
Pull request merged. Thank you!
